download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/community-rabbitmq-1.6.0.tar.gz
format_version: 1.0.0
name: rabbitmq
namespace: community
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.6.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/community/rabbitmq/versions/1.6.0/
