download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/openvswitch-openvswitch-2.1.1.tar.gz
format_version: 1.0.0
name: openvswitch
namespace: openvswitch
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.1.1
version_url: /api/v3/plugin/ansible/content/published/collections/index/openvswitch/openvswitch/versions/2.1.1/
